server:
  port: 80

spring:
  application:
    name: cloud-consumerconsul-order
  cloud:
    consul:
      host: 192.168.98.27
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
        port: ${server.port}

