server:
  port: 9002

spring:
  application:
    name: nacos-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.98.27:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'