server:
  port: 3344

spring:
  application:
    name: cloud-config-center3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chensjian/springcloud-config.git #github上面的git仓库名字
          ##搜索目录
          search-paths:
            - springcloud-config
#          skip-ssl-validation: true
          username: 2811908526@qq.com
          password: 20010827csj
      #读取分支
      label: main
eureka:
  instance:
    instance-id: cloud-config-center
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka





