server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.98.27:8848 #nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.98.27:8080
        port: 8719
        datasource:
          ds1:
            nacos:
              server-addr: 192.168.98.27:8848
              dataId: cloudalibaba-sentinel-service
              groupId: DEFAULT_GROUP
              data-type: json
              rule-type: flow

#    sentinel:
#      transport:
#        dashboard: localhost:8080 #配置sentinel dashboard地址
#        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描，直至找到未被占用的端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
