server:
  port: 8006
spring:
  application:
    name: cloud-providerconsul-payment
  cloud:
    consul:
      host: 192.168.98.27
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: true
        port: ${server.port}


