server:
  port: 9527

spring:
  application:
    name: cloud-gateway-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh  #payment_route  路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**   #断言，路径相匹配的进行路由

        - id: payment_routh2  #payment_route   #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: gateway9527
