server:
  port: 2001
spring:
  application:
    name: seata-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.98.27:3306/seata_order?serverTimezone=Asia/Shanghai
    username: root
    password: 20010827Csj@
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.98.27:8848
    alibaba:
      seata:
        #该值必须和config.txt文件中的分组名一致
        tx-service-group: fuzhou
      #自定义事务组名称需要与seata-service中的对应


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chen.springcloud.domain

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.98.27:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP

      namespace: "ed67ace5-8e2c-49c7-a9f4-cf3ab44901e3"
  config:
    type: nacos
    nacos:
      server-addr: 192.168.98.27:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP

feign:
  client:
    config:
      seata-account-service:
        readTimeout: 3000
