server:
  port: 83
spring:
  application:
    name: nacos-consumer-order83
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.98.27:8848

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-url-service: http://nacos-provider-payment
management:
  endpoints:
    web:
      exposure:
        include: "*"