server:
  port: 83
spring:
  application:
    name: cloudalibaba-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.98.27:8848
    sentinel:
      transport:
        dashboard: 192.168.98.27:8080
        port: 8719

# 激活Sentinel对feign的支持
feign:
  sentinel:
    enabled: true
