server:
  port: 2003
spring:
  application:
    name: seata-storage-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.98.27:8848
    alibaba:
      seata:
        tx-service-group: fuzhou
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.98.27:3306/seata_storage?serverTimezone=UTC
    username: root
    password: 20010827Csj@

seata:
  registry:
    nacos:

      server-addr: 192.168.98.27:8848
      username: nacos
      password: nacos
      application: seata-server
      namespace: "ed67ace5-8e2c-49c7-a9f4-cf3ab44901e3"
      group: SEATA_GROUP
    type: nacos
  config:
    nacos:
      server-addr: 192.168.98.27:8848
      username: nacos
      password: nacos
    type: nacos



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chen.springcloud.domain
